version: "3"

services:
  node:
     build: ./backend
     depends_on:
       - sql
     env_file:
        - ./docker-compose-lesson.env
     environment:
        - MYSQL_HOST=sql
     ports:
        - 8080:4200
     volumes:
     - ./backend:/home/node/app
  nginx:
     build: ./frontend
     depends_on:
        - node
     volumes:
        - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
     ports:
        - 80:80
  sql:
    build: ./sql
    env_file:
       - ./docker-compose-lesson.env
    volumes:
     - compose-lesson:/var/lib/mysql
    ports:
       - 33006:3306
volumes:
  compose-lesson: