version: "3"

services:
  backend:
     build: ./backend
     depends_on:
       - mysql
     env_file:
        - ./docker-compose-lesson.env
     environment:
        - MYSQL_HOST=mysql
     ports:
        - 8001:80
  frontend:
     build: ./frontend
     depends_on:
        - backend
     volumes:
        - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
     ports:
        - 8002:80
  mysql:
    build: ./mysql
    env_file:
       - ./docker-compose-lesson.env
    ports:
       - 33006:3306