version: "3"

services:
  php:
     build: ./php
     depends_on:
       - sql
     env_file:
        - ./docker-compose-lesson.env
     environment:
        - MYSQL_HOST=sql
     ports:
        - 8001:80
  frontend:
     build: ./frontend
     depends_on:
        - php
     volumes:
        - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
     ports:
        - 8002:80
  sql:
    build: ./sql
    env_file:
       - ./docker-compose-lesson.env
    volumes:
     - compose-lesson:/var/lib/mysql
    ports:
       - 33006:3306
volumes:
  compose-lesson: